
INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('TITLE1', 'CONTENTSSSS1111', 'SONG');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('TITLE2', 'CONTENTSSSS2222', 'KIM');

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('TITLE3', 'CONTENTSSSS33333', 'PARK');
