DROP TABLE IF EXISTS BOARD;

CREATE TABLE BOARD(
    ID NUMBER IDENTITY PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(200) NOT NULL,
    CONTENT VARCHAR(1000) NOT NULL,
    REGDATE DATE DEFAULT SYSDATE,
    WRITER VARCHAR(50) NOT NULL
);
